### ISSUE TITLE
Error: Type '"LinkedList"' is not assignable to type...

### ISSUE THREAD

**Issue by carlo-quinonez** [ptc-iot-sharing/ThingworxVSCodeProject#19]
I'm not sure what's causing this error, but I can build the sample files only if I comment out lines 137-142 in `src/MyThing.ts`. 

![image](https://user-images.githubusercontent.com/53790047/114113208-fa7bda00-9892-11eb-88c8-fd3fe3a3483a.png)

**Comment by BogdanMihaiciuc** [comment]
This happens when the declarations for the Thingworx collections aren't generated or stale.

To resolve this, run `gulp` with no arguments and leave it running while working. You can check the generated declarations in `/static/gen/Generated.d.ts`. Note that by default these are excluded from git through gitignore.

You should be able to build in a separate terminal.

**Comment by carlo-quinonez** [comment]
got it! Thank you, this seemed to fix the problem

**Comment by carlo-quinonez** [comment]
@BogdanMihaiciuc What is the gulp task that refreshes the declarations in `/static/gen/Generated.d.ts`?

I'd like to this up as part of an automated CICD pipeline, so I need to call that task explicitly.

**Comment by BogdanMihaiciuc** [comment]
It is the default task implemented in the `gen` function in the gulp file. You will need to modify or duplicate it in order to generate the declarations on demand since that task launches a watcher that executes a piece of code when any source file is changed.

It might make sense to separate out that portion as its own task and just add it as the first one in the build series.

**Comment by BogdanMihaiciuc** [comment]
The latest gulp file now generates declarations as the first step in building the project.
