### ISSUE TITLE
LinkedList not a valid DataShape

### ISSUE THREAD

**Issue by ThibaultGeorges** [ptc-iot-sharing/ThingworxVSCodeProject#2]
Error when using out of the box c84f1d83b29d5f6a9ff67ba7da6a5b4548bbf0ec
> src/MyThing.ts(131,82): error TS2322: Type '"LinkedList"' is not assignable to type '"LicenseGroupUsageDataShape" | "DTAuditShape" | "DesignTimePermissions" | "EntityReferenceWithDescription" | "UserProvisioningUserExclusionList" | "AnalyticsSignalsResult" | ... 328 more ... | undefined'.
> TypeScript: 1 semantic error
> TypeScript: emit succeeded (with errors)

Analysis:
- class LinkedList is defined in MyDataShape.ts and extends DataShapeBase
- In MyThing.ts, in streamToUseChanged method, call to Resources.InfoTableFunctions.CreateInfoTableFromDataShape function requires its dataShapeName parameter to refer to some item which extends DATASHAPENAME (= keyof DataShapes).
- but LinkedList is not in this list
- this list may not be modified as it is under static/base

Why is MyThing.ts not aware of DataShape definitions which are part of the projet ?

**Comment by BogdanMihaiciuc** [comment]
The provided example doesn't compile directly because the only declarations that are actually included in the project are those that are part of an empty installation of Thingworx, so none of the classes under `src` are there, which means you can't reference them via their collections (e.g. `DataShapes.MyDataShape`). 

You should be able to reference it via the class name (e.g. writing `INFOTABLE<LinkedList>`), however TypeScript is not normally aware that classes can be referenced via collections (writing `DataShapes.LinkedList`) so there is a separate process that creates this linking.

This is why it's important to run `gulp` and leave it running. This is a watch process that will generate those declarations whenever you save a file. It will generate the `static/gen/Generated.d.ts` file which will look like this for the example entities:
```ts
declare interface DataShapes { MyDataShape: DataShapeEntity<MyDataShape> }

declare interface ThingShapes { MyThingShape: ThingShapeEntity<MyThingShape> }
...
```

An annoyance with this right now is that you need to actually save a file in order to get these declarations. Just running `gulp` will not create it directly.

**Comment by ThibaultGeorges** [comment]
Thanks for your answer.
Running gulp fixed the issue. I had to run it twice to get the expected Generated.d.ts file. gulp build was indeed not sufficient.
I had to add gulp as a task, besides build and upload, in order for it to be executed. Running it from command line was not working. I assume it is due to running with WSL2 setup.

In the meantime, I worked around by adding those lines you mentionned to original source files.
