### ISSUE TITLE
Issue with Stream Entity, Things with scheduler as  base 

### ISSUE THREAD

**Issue by thomas-thomas-tfs** [ptc-iot-sharing/ThingworxVSCodeProject#23]
- [ ] Data Shapes extended with streams are not getting added to resultant Stream
- [ ]  How to provide @schedule and run as params for things to be created from Scheduler Thing

**Comment by carlo-quinonez** [comment]
What have you considered for setting configurations and property values? Some of these are per-environment in our case, and I'd love to be able to inject the appropriate per-env values at build time.

**Comment by BogdanMihaiciuc** [comment]
I was considering having a separate file, like a json or env file, that would contain these runtime values. 

I'm open to suggestions on how to best handle this use case.

It's technically easy to do, since these values can be specified in the generated xml, but I haven't yet found an approach I'm happy with.
